CREATE TABLE IF NOT EXISTS account (
	id		INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name		TEXT NOT NULL UNIQUE,
	options		TEXT NULL
	);
CREATE TABLE IF NOT EXISTS folder (
	id		INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	accountid	INTEGER NOT NULL REFERENCES account(id) ON DELETE CASCADE,
	parentid	INTEGER NULL REFERENCES folder(id) ON DELETE CASCADE,
	name		TEXT NOT NULL,
	flags		INTEGER NULL
	);
