QT       += core gui
TARGET = qtpuzzle
TEMPLATE = app
SOURCES += main.cpp mainwindow.cpp
HEADERS  += mainwindow.h
FORMS    += mainwindow.ui
RESOURCES += images.qrc
target.path = /usr/bin
desktop.path = /usr/share/applications
desktop.files = qtpuzzle.desktop
#icon.path = /usr/share/pixmaps
#icon.files = qtrun.png
INSTALLS += target desktop
CONFIG += warn_on
