# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/shares/home/eugene/Version/SVN/qtdesktop/trunk/pyqtarc/ui/main.ui'
#
# Created: Sun Nov 18 19:23:32 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName(_fromUtf8("Main"))
        Main.resize(288, 253)
        Main.setWindowTitle(_fromUtf8("QtArc"))
        self.centralwidget = QtGui.QWidget(Main)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeView = QtGui.QTreeView(self.centralwidget)
        self.treeView.setAcceptDrops(True)
        self.treeView.setDragEnabled(True)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.verticalLayout.addWidget(self.treeView)
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 288, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menu_Actions = QtGui.QMenu(self.menubar)
        self.menu_Actions.setObjectName(_fromUtf8("menu_Actions"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        Main.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Main)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Main.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(Main)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        Main.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_FileNew = QtGui.QAction(Main)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/24x24/document-new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_FileNew.setIcon(icon)
        self.action_FileNew.setShortcut(_fromUtf8("Ctrl+N"))
        self.action_FileNew.setIconVisibleInMenu(True)
        self.action_FileNew.setObjectName(_fromUtf8("action_FileNew"))
        self.action_FileOpen = QtGui.QAction(Main)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/24x24/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_FileOpen.setIcon(icon1)
        self.action_FileOpen.setShortcut(_fromUtf8("Ctrl+O"))
        self.action_FileOpen.setIconVisibleInMenu(True)
        self.action_FileOpen.setObjectName(_fromUtf8("action_FileOpen"))
        self.action_FileSaveAs = QtGui.QAction(Main)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/24x24/document-save-as.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_FileSaveAs.setIcon(icon2)
        self.action_FileSaveAs.setShortcut(_fromUtf8("Ctrl+S"))
        self.action_FileSaveAs.setIconVisibleInMenu(True)
        self.action_FileSaveAs.setObjectName(_fromUtf8("action_FileSaveAs"))
        self.action_Extract = QtGui.QAction(Main)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/24x24/extract-archive.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Extract.setIcon(icon3)
        self.action_Extract.setShortcut(_fromUtf8("Ctrl+E"))
        self.action_Extract.setIconVisibleInMenu(True)
        self.action_Extract.setObjectName(_fromUtf8("action_Extract"))
        self.action_FileProperties = QtGui.QAction(Main)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/24x24/document-properties.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_FileProperties.setIcon(icon4)
        self.action_FileProperties.setShortcut(_fromUtf8("Ctrl+P"))
        self.action_FileProperties.setIconVisibleInMenu(True)
        self.action_FileProperties.setObjectName(_fromUtf8("action_FileProperties"))
        self.action_Exit = QtGui.QAction(Main)
        self.action_Exit.setShortcut(_fromUtf8("Ctrl+Q"))
        self.action_Exit.setIconVisibleInMenu(True)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.action_AddFile = QtGui.QAction(Main)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/24x24/add-files-to-archive.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_AddFile.setIcon(icon5)
        self.action_AddFile.setShortcut(_fromUtf8("Ctrl+F"))
        self.action_AddFile.setIconVisibleInMenu(True)
        self.action_AddFile.setObjectName(_fromUtf8("action_AddFile"))
        self.action_AddDirectory = QtGui.QAction(Main)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/24x24/add-folder-to-archive.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_AddDirectory.setIcon(icon6)
        self.action_AddDirectory.setShortcut(_fromUtf8("Ctrl+D"))
        self.action_AddDirectory.setIconVisibleInMenu(True)
        self.action_AddDirectory.setObjectName(_fromUtf8("action_AddDirectory"))
        self.action_EditCut = QtGui.QAction(Main)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/24x24/edit-cut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_EditCut.setIcon(icon7)
        self.action_EditCut.setShortcut(_fromUtf8("Ctrl+X"))
        self.action_EditCut.setIconVisibleInMenu(True)
        self.action_EditCut.setObjectName(_fromUtf8("action_EditCut"))
        self.action_EditCopy = QtGui.QAction(Main)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/24x24/edit-copy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_EditCopy.setIcon(icon8)
        self.action_EditCopy.setShortcut(_fromUtf8("Ctrl+C"))
        self.action_EditCopy.setIconVisibleInMenu(True)
        self.action_EditCopy.setObjectName(_fromUtf8("action_EditCopy"))
        self.action_EditPaste = QtGui.QAction(Main)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/24x24/edit-paste.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_EditPaste.setIcon(icon9)
        self.action_EditPaste.setShortcut(_fromUtf8("Ctrl+V"))
        self.action_EditPaste.setIconVisibleInMenu(True)
        self.action_EditPaste.setObjectName(_fromUtf8("action_EditPaste"))
        self.action_Delete = QtGui.QAction(Main)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/24x24/edit-delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Delete.setIcon(icon10)
        self.action_Delete.setShortcut(_fromUtf8("Del"))
        self.action_Delete.setIconVisibleInMenu(True)
        self.action_Delete.setObjectName(_fromUtf8("action_Delete"))
        self.action_HelpAbout = QtGui.QAction(Main)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/24x24/help-about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_HelpAbout.setIcon(icon11)
        self.action_HelpAbout.setShortcut(_fromUtf8(""))
        self.action_HelpAbout.setIconVisibleInMenu(True)
        self.action_HelpAbout.setObjectName(_fromUtf8("action_HelpAbout"))
        self.action_HelpAboutQt = QtGui.QAction(Main)
        self.action_HelpAboutQt.setShortcut(_fromUtf8(""))
        self.action_HelpAboutQt.setObjectName(_fromUtf8("action_HelpAboutQt"))
        self.action_EditSelectAll = QtGui.QAction(Main)
        self.action_EditSelectAll.setShortcut(_fromUtf8("Ctrl+A"))
        self.action_EditSelectAll.setIconVisibleInMenu(True)
        self.action_EditSelectAll.setObjectName(_fromUtf8("action_EditSelectAll"))
        self.action_EditDeselect = QtGui.QAction(Main)
        self.action_EditDeselect.setShortcut(_fromUtf8("Ctrl+Shift+A"))
        self.action_EditDeselect.setIconVisibleInMenu(True)
        self.action_EditDeselect.setObjectName(_fromUtf8("action_EditDeselect"))
        self.action_ViewTree = QtGui.QAction(Main)
        self.action_ViewTree.setCheckable(True)
        self.action_ViewTree.setObjectName(_fromUtf8("action_ViewTree"))
        self.action_ViewTable = QtGui.QAction(Main)
        self.action_ViewTable.setCheckable(True)
        self.action_ViewTable.setObjectName(_fromUtf8("action_ViewTable"))
        self.action_ViewIcons = QtGui.QAction(Main)
        self.action_ViewIcons.setCheckable(True)
        self.action_ViewIcons.setObjectName(_fromUtf8("action_ViewIcons"))
        self.action_ViewColumns = QtGui.QAction(Main)
        self.action_ViewColumns.setCheckable(True)
        self.action_ViewColumns.setObjectName(_fromUtf8("action_ViewColumns"))
        self.menu_File.addAction(self.action_FileNew)
        self.menu_File.addAction(self.action_FileOpen)
        self.menu_File.addAction(self.action_FileSaveAs)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_FileProperties)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menu_Edit.addAction(self.action_EditCut)
        self.menu_Edit.addAction(self.action_EditCopy)
        self.menu_Edit.addAction(self.action_EditPaste)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_EditSelectAll)
        self.menu_Edit.addAction(self.action_EditDeselect)
        self.menu_Help.addAction(self.action_HelpAbout)
        self.menu_Help.addAction(self.action_HelpAboutQt)
        self.menu_Actions.addAction(self.action_AddFile)
        self.menu_Actions.addAction(self.action_AddDirectory)
        self.menu_Actions.addAction(self.action_Extract)
        self.menu_Actions.addAction(self.action_Delete)
        self.menu_View.addAction(self.action_ViewTree)
        self.menu_View.addAction(self.action_ViewTable)
        self.menu_View.addAction(self.action_ViewIcons)
        self.menu_View.addAction(self.action_ViewColumns)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Actions.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.action_FileNew)
        self.toolBar.addAction(self.action_FileOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_AddFile)
        self.toolBar.addAction(self.action_AddDirectory)
        self.toolBar.addAction(self.action_Extract)
        self.toolBar.addAction(self.action_Delete)

        self.retranslateUi(Main)
        QtCore.QObject.connect(self.action_Exit, QtCore.SIGNAL(_fromUtf8("triggered()")), Main.close)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        self.menu_File.setTitle(QtGui.QApplication.translate("Main", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("Main", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("Main", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Actions.setTitle(QtGui.QApplication.translate("Main", "&Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_View.setTitle(QtGui.QApplication.translate("Main", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("Main", "ToolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_FileNew.setText(QtGui.QApplication.translate("Main", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.action_FileOpen.setText(QtGui.QApplication.translate("Main", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_FileSaveAs.setText(QtGui.QApplication.translate("Main", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Extract.setText(QtGui.QApplication.translate("Main", "&Extract", None, QtGui.QApplication.UnicodeUTF8))
        self.action_FileProperties.setText(QtGui.QApplication.translate("Main", "&Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setText(QtGui.QApplication.translate("Main", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_AddFile.setText(QtGui.QApplication.translate("Main", "Add &File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_AddDirectory.setText(QtGui.QApplication.translate("Main", "Add &Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.action_EditCut.setText(QtGui.QApplication.translate("Main", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.action_EditCopy.setText(QtGui.QApplication.translate("Main", "&Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.action_EditPaste.setText(QtGui.QApplication.translate("Main", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Delete.setText(QtGui.QApplication.translate("Main", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.action_HelpAbout.setText(QtGui.QApplication.translate("Main", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_HelpAboutQt.setText(QtGui.QApplication.translate("Main", "AboutQt", None, QtGui.QApplication.UnicodeUTF8))
        self.action_EditSelectAll.setText(QtGui.QApplication.translate("Main", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.action_EditDeselect.setText(QtGui.QApplication.translate("Main", "Deselect", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ViewTree.setText(QtGui.QApplication.translate("Main", "T&ree", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ViewTable.setText(QtGui.QApplication.translate("Main", "&Table", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ViewIcons.setText(QtGui.QApplication.translate("Main", "&Icons", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ViewColumns.setText(QtGui.QApplication.translate("Main", "&Columns", None, QtGui.QApplication.UnicodeUTF8))

import pyqtarc_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Main = QtGui.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())

