######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 21 17:26:40 2011
######################################################################

QT = core gui network

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myftp.h
SOURCES += main.cpp myftp.cpp
