######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 24 14:06:18 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qtzip.cpp
