# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/shares/home/eugene/Version/SVN/qtdesktop/trunk/qgooglepim/src/ui/main.ui'
#
# Created: Wed Dec  1 22:09:05 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(411, 322)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/ui/img/35x35/google.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 411, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuService = QtGui.QMenu(self.menubar)
        self.menuService.setObjectName("menuService")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBase = QtGui.QAction(MainWindow)
        self.actionBase.setObjectName("actionBase")
        self.actionBlog = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/ui/img/google/blogger.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBlog.setIcon(icon1)
        self.actionBlog.setObjectName("actionBlog")
        self.actionCalendar = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/ui/img/google/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCalendar.setIcon(icon2)
        self.actionCalendar.setObjectName("actionCalendar")
        self.actionDocs = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/ui/img/google/docs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocs.setIcon(icon3)
        self.actionDocs.setObjectName("actionDocs")
        self.actionMail = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/ui/img/google/mail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMail.setIcon(icon4)
        self.actionMail.setObjectName("actionMail")
        self.actionPicasa = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/ui/img/google/picasa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPicasa.setIcon(icon5)
        self.actionPicasa.setObjectName("actionPicasa")
        self.actionContacts = QtGui.QAction(MainWindow)
        self.actionContacts.setObjectName("actionContacts")
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNotebook = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/ui/img/35x35/notebook.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNotebook.setIcon(icon6)
        self.actionNotebook.setObjectName("actionNotebook")
        self.actionCode = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/ui/img/google/code.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCode.setIcon(icon7)
        self.actionCode.setObjectName("actionCode")
        self.menuFile.addAction(self.actionExit)
        self.menuService.addAction(self.actionBase)
        self.menuService.addAction(self.actionBlog)
        self.menuService.addAction(self.actionCalendar)
        self.menuService.addAction(self.actionContacts)
        self.menuService.addAction(self.actionDocs)
        self.menuService.addAction(self.actionNotebook)
        self.menuService.addAction(self.actionMail)
        self.menuService.addAction(self.actionPicasa)
        self.menuService.addAction(self.actionCode)
        self.menuService.addSeparator()
        self.menuService.addAction(self.actionSettings)
        self.menuService.addAction(self.actionConnect)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuService.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "GooglePIM", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuService.setTitle(QtGui.QApplication.translate("MainWindow", "&Service", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBase.setText(QtGui.QApplication.translate("MainWindow", "&Base", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBlog.setText(QtGui.QApplication.translate("MainWindow", "B&log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalendar.setText(QtGui.QApplication.translate("MainWindow", "&Calendar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocs.setText(QtGui.QApplication.translate("MainWindow", "&Docs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMail.setText(QtGui.QApplication.translate("MainWindow", "&Mail", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPicasa.setText(QtGui.QApplication.translate("MainWindow", "&Picasa", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContacts.setText(QtGui.QApplication.translate("MainWindow", "&Contacts", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setText(QtGui.QApplication.translate("MainWindow", "Co&nnect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNotebook.setText(QtGui.QApplication.translate("MainWindow", "&Notebook", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCode.setText(QtGui.QApplication.translate("MainWindow", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCode.setToolTip(QtGui.QApplication.translate("MainWindow", "Google Code Issues", None, QtGui.QApplication.UnicodeUTF8))

import googlepim_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

