######################################################################
# Automatically generated by qmake (2.01a) ?r. sty 28 17:03:58 2009
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qwwsmtpclient.cpp
HEADERS += qwwsmtpclient.h

QT += network

