CREATE TABLE IF NOT EXISTS p (
	id		INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name		TEXT NOT NULL UNIQUE,
	programm	TEXT NOT NULL,
	port		INTEGER NOT NULL,
	term		BOOLEAN NOT NULL DEFAULT False,
	cmdline		TEXT NOT NULL,
	logo		BLOB NULL DEFAULT NULL
	);
CREATE TABLE IF NOT EXISTS v (
	id		INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	protoid		INTEGER NOT NULL,
	name		TEXT NOT NULL UNIQUE,
	val		TEXT NULL
	);
CREATE TABLE IF NOT EXISTS h (
	id		INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name		TEXT NOT NULL UNIQUE,
	val		TEXT NOT NULL UNIQUE
	);
CREATE TABLE IF NOT EXISTS h (
	id		INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name		TEXT NOT NULL UNIQUE,
	protoid		INTEGER NOT NULL,
	hostid		INTEGER NOT NULL,
	port		INTEGER NULL,
	varid		INTEGER NULL,
	cmdline		TEXT NULL,
	comments	TEXT NULL
	);
CREATE TRIGGER p_d
	BEFORE
	DELETE
	ON main.p
	FOR EACH ROW
	BEGIN
		DELETE FROM v WHERE protoid=old.id;
		DELETE FROM c WHERE protoid=old.id;
	END;
CREATE TRIGGER v_d
	BEFORE
	DELETE
	ON main.v
	FOR EACH ROW
	BEGIN
		UPDATE c SET varid = NULL WHERE varid=old.id;
	END;
CREATE TRIGGER h_d
	BEFORE
	DELETE
	ON main.h
	FOR EACH ROW
	BEGIN
		DELETE FROM c WHERE hostid=old.id;
	END;
