## Generated by HaiQ on ?? ???. 18 2008

TEMPLATE = lib
CONFIG += qt plugin
QT += core gui network xml
TARGET = ../weather
INCLUDEPATH += \
	../../include \
	/usr/include

HEADERS +=  \
	weatherPlugin.h \
	weatherSettings.h
	
SOURCES += \
	weatherPlugin.cpp \
	weatherSettings.cpp
	
FORMS += \
	weatherSettings.ui
	
RESOURCES += weather.qrc
