## Generated by HaiQ on Sat Nov 15 2008

TEMPLATE = lib
CONFIG += qt plugin
DEPENDPATH += .
INCLUDEPATH += . /usr/include
TARGET = ../protocolicon
DEPENDPATH += .
QT += core gui xml

HEADERS +=  protocolicon.h
SOURCES += protocolicon.cpp
FORMS += pluginsettings.ui
RESOURCES += protocolicon.qrc



